use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
#[allow(dead_code)]
pub struct Entry {
    pub uid: String,

    // Generated by MX. Users never submit or edit this value.
    // The number is unique only inside its year and resets to 1 for a new year.
    pub control_no: u64,

    pub date: String,
    pub office: String,
    pub requestor: String,
    pub subject: String,
    pub routed_to_div: String,

    #[serde(default)]
    pub attached_files: Vec<FileAttachment>,

    pub remarks: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
#[allow(dead_code)]
pub struct CreateEntryRequest {
    pub date: String,
    pub office: String,
    pub requestor: String,
    pub subject: String,
    pub routed_to_div: String,
    pub remarks: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
#[allow(dead_code)]
pub struct UpdateEntryRequest {
    pub date: String,
    pub office: String,
    pub requestor: String,
    pub subject: String,
    pub routed_to_div: String,
    pub remarks: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct FileAttachment {
    pub uid: String,
    pub file_name: String,
    pub mime_type: String,
    pub size: u64,

    // Human-navigable N1 namespace key, for example:
    // records/<configured-folders>/<file-attachment-field>/document.pdf
    pub object_key: String,

    pub version_id: Option<String>,

    // New uploads always carry their File Attachment field identity.
    // Option remains for safe deserialization/migration of historical metadata.
    #[serde(default)]
    pub attachment_field_uid: Option<String>,

    #[serde(default)]
    pub attachment_field_label: Option<String>,

    #[serde(default)]
    pub attachment_field_storage_name: Option<String>,
}
