<script lang="ts">
  import {relatedRecords,type RelatedRecord} from '../api/relationships';
  let {module,record}:{module:string;record:string}=$props();
  let page=$state(1);let items=$state<RelatedRecord[]>([]);let more=$state(false);let error=$state('');let loading=$state(false);
  let expanded=$state(false);
  $effect(()=>{const id=record;const source=module;const number=page;if(!expanded)return;const controller=new AbortController();loading=true;void relatedRecords(source,id,number,controller.signal).then(result=>{if(controller.signal.aborted)return;items=result.items;more=result.has_next;error='';}).catch(reason=>{if(!controller.signal.aborted)error=String(reason);}).finally(()=>{if(!controller.signal.aborted)loading=false;});return()=>controller.abort();});
</script>
<details class="related-records" ontoggle={event=>expanded=event.currentTarget.open}><summary>Related records</summary><p class="muted small">Records that reference this entry. Only accessible modules are shown.</p>{#if error}<p role="alert">{error}</p>{:else if loading}<p>Loading…</p>{:else}{#each items as item}<a href={`#module/${encodeURIComponent(item.module_uid)}?record=${encodeURIComponent(item.uid)}`}><strong>{item.module_name}</strong><span>{item.label} · via {item.relationship_label}</span></a>{:else}<p class="muted small">No accessible records reference this entry.</p>{/each}{#if page>1||more}<div class="inline-actions"><button class="button small" type="button" disabled={page===1} onclick={()=>page--}>Previous</button><span>Page {page}</span><button class="button small" type="button" disabled={!more} onclick={()=>page++}>Next</button></div>{/if}{/if}</details>
<style>.related-records{border-top:1px solid var(--line);padding:1rem 0;grid-column:1/-1}summary{cursor:pointer;font-weight:600}a{display:flex;flex-wrap:wrap;gap:.6rem;padding:.65rem;border:1px solid var(--line);border-radius:.4rem;margin:.4rem 0;color:var(--text);text-decoration:none}a:hover{background:var(--surface-2)}a span{color:var(--muted);font-size:.8rem}</style>
